import { SquareTerminal } from "lucide-react";

export const JAVASCRIPT_TOPICS = {
  tech_topic: "JavaScript",
  is_default_open: true,
  is_open: false,
  order_index: 1,
  topics: [
    {
      index: "1.",
      title: "1. Types, Values, and Variables",
      is_default_open: true,
      is_open: false,
      number_of_sub_topics: 5,
      difficulty_level: 1,
      sub_topics: [
        {
          index: "1.1.",
          title: "1.1. Numbers",
          url: "#",
          difficulty_level: 1,
          icon: SquareTerminal,
          is_default_open: true,
          is_open: false,
          is_lessons_started: false,
          lessons: [
            {
              index: "1.1.1.",
              title: "1.1.1. Integer Literals",
              url: "*",
              is_lesson_correct: false,
              is_lesson_started: false,
              icon: SquareTerminal,
              difficulty_level: 1,
            },
            {
              index: "1.1.2.",
              title: "1.1.2. Floating-Point Literals",
              url: "*",
              is_lesson_correct: false,
              is_lesson_started: false,
              icon: SquareTerminal,
              difficulty_level: 1,
            },
            {
              index: "1.1.3.",
              title: "1.1.3. Arithmetic in JavaScript",
              url: "*",
              is_lesson_correct: false,
              is_lesson_started: false,
              icon: SquareTerminal,
              difficulty_level: 1,
            },
            {
              index: "1.1.4.",
              title: "1.1.4. Dates and Times",
              url: "*",
              is_lesson_correct: false,
              is_lesson_started: false,
              icon: SquareTerminal,
              difficulty_level: 1,
            },
          ],
        },
        {
          index: "1.2.",
          title: "1.2. Boolean values",
          url: "#",
          difficulty_level: 1,
          icon: SquareTerminal,
          is_default_open: true,
          is_open: false,
          is_lessons_started: false,
          lessons: [
            {
              index: "1.2.1.",
              title: "1.2.1. What's Boolean",
              url: "*",
              is_lesson_correct: false,
              is_lesson_started: false,
              icon: SquareTerminal,
              difficulty_level: 1,
            },
          ],
        },
        {
          index: "1.3.",
          title: "1.3. null and undefined",
          url: "#",
          difficulty_level: 1,
          icon: SquareTerminal,
          is_default_open: false,
          is_open: false,
          is_lessons_started: false,
          lessons: [
            {
              index: "1.3.1.",
              title: "1.3.1. What is null",
              url: "*",
              is_lesson_correct: false,
              is_lesson_started: false,
              icon: SquareTerminal,
              difficulty_level: 1,
            },
            {
              index: "1.3.2.",
              title: "1.3.2. What is undefined",
              url: "*",
              is_lesson_correct: false,
              is_lesson_started: false,
              icon: SquareTerminal,
              difficulty_level: 1,
            },
          ],
        },
      ],
    },
  ],
};
